apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: servicio-ingress-catalog
spec:
  ingressClassName: nginx
  rules:
  - host: chaphe-bookstore.catalog.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-catalog-service
            port:
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: servicio-ingress-reviews
spec:
  ingressClassName: nginx
  rules:
  - host: chaphe-bookstore.reviews.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-reviews-service
            port:
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: servicio-ingress-store
spec:
  ingressClassName: nginx
  rules:
  - host: chaphe-bookstore.store.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-store-service
            port:
              number: 80
